# Label configuration for the project
# Used by GitHub Actions label sync workflow
---
labels:
  - name: "bug"
    color: "d73a4a"
    description: "Something isn't working"
  - name: "enhancement"
    color: "a2eeef"
    description: "New feature or request"
  - name: "documentation"
    color: "0075ca"
    description: "Improvements or additions to documentation"
  - name: "good first issue"
    color: "7057ff"
    description: "Good for newcomers"
  - name: "priority: high"
    color: "ff0000"
    description: "High priority"
  - name: "priority: medium"
    color: "ffa500"
    description: "Medium priority"
  - name: "priority: low"
    color: "ffff00"
    description: "Low priority"
  - name: "help wanted"
    color: "008080"
    description: "Extra attention is needed"
  - name: "wontfix"
    color: "ffffff"
    description: "This will not be worked on"
  - name: "duplicate"
    color: "cccccc"
    description: "This already exists"
  - name: "accessibility"
    color: "9400D3"
    description: "Related to accessibility improvements"
  - name: "performance"
    color: "32CD32"
    description: "Related to performance improvements"
  - name: "security"
    color: "FF4500"
    description: "Related to security fixes"
  - name: "czech"
    color: "D21F3C"
    description: "Czech market specific"
  - name: "seo"
    color: "1E90FF"
    description: "Search engine optimization"
